# Generated by Django 5.2.1 on 2025-08-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_alter_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='end_time',
            new_name='shift_end_time',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='start_time',
            new_name='shift_start_time',
        ),
    ]
